### ISSUE TITLE
About 3d joints pre-processing

### ISSUE THREAD

**Issue by xy-guo** [nkolot/SPIN#17]
In 3d joints augmentation, why only permute x and y coordinates? 

https://github.com/nkolot/SPIN/blob/a5c629f993b6fdb006d5f0a020bcecbe4c5ccfbb/datasets/base_dataset.py#L160

**Comment by geopavlakos** [comment]
The last column of S corresponds to the flag whether the relevant 3D joint exists or not, not to the z coordinate. This operation doesn't affect us, since for the datasets we use, either both left/right 3D joints exist or both of them do not exist. However, we did update the code to handle more generic input. Thanks for pointing this out!

**Comment by xy-guo** [comment]
Thank you so much!
