### ISSUE TITLE
How to get h36m_single_train_openpose.npz?

### ISSUE THREAD

**Issue by BICHENG** [nkolot/SPIN#20]
What's the data included in h36m_single_train_openpose?
How to generate h36m_single_train_openpose.npz?
Where can I find h36m_single_train_openpose.npz?

Any example?

**Comment by geopavlakos** [comment]
This file includes the data for Human3.6M and is similar to the other .npz files we released. Besides image names, scale/center and 2D/3D/openpose joints, it also includes pose and shape parameters for the Human3.6M dataset. Due to the dataset license, we cannot release it, but if you have the data, it should be straightforward to produce it, if you also take a look to the other dataset preprocessing scripts we provide.

**Comment by BICHENG** [comment]
Could you please add this h36m script to this repository?

**Comment by geopavlakos** [comment]
The script is already in SPIN/datasets/preprocess/h36m_train.py. I updated it to include the reading of the openpose predictions, but you will still need to read and include the SMPL pose and shape parameters in the .npz file (in case you have access to them).

**Comment by liwenssss** [comment]
if I have h36m dataset , how can I generate pose and betas paramers?

**Comment by geopavlakos** [comment]
We used pose and shape parameters generated by the [MoSh method](http://mosh.is.tue.mpg.de). However, due to license implications, this data is not public. You could try to fit SMPL to the 3D keypoints of the dataset. This would probably be less accurate, but it should give you reasonable results.

**Comment by liwenssss** [comment]
Do you generate pose and shape parameters of MPI-INF-3DHP in the same way?

**Comment by geopavlakos** [comment]
No MoSh results are available for MPI-INF-3DHP. In that case, we fit SMPL to keypoints. Since ground truth is not very accurate, we prefer to use OpenPose predictions and fit SMPL to them for all viewpoints simultaneously.

**Comment by liwenssss** [comment]
Sorry, I can't find any tutorial about how to use MoSh to get the parameters. Can you offer some links?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Georgios Pavlakos"<notifications@github.com&gt;; 
发送时间: 2019年12月3日(星期二) 晚上10:43
收件人: "nkolot/SPIN"<SPIN@noreply.github.com&gt;; 
抄送: "李文盛"<573014453@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [nkolot/SPIN] How to get h36m_single_train_openpose.npz? (#20)




We used pose and shape parameters generated by the MoSh method. However, due to license implications, this data is not public. You could try to fit SMPL to the 3D keypoints of the dataset. This would probably be less accurate, but it should give you reasonable results.

**Comment by geopavlakos** [comment]
The code for the MoSh approach is not publicly available. You could refer to the description of the paper for more details.

**Comment by GuiZhaoyang** [comment]
@geopavlakos hi,Could I know how to fit SMPL to the 3D keypoints of the h36m dataset?Because I have not the Mocap annotation but I have the 3D keypoints annotation.May I know the code to to fit SMPL to the 3D keypoints?

**Comment by vigorbird** [comment]
@GuiZhaoyang 兄弟留个邮箱，有偿求human3.6m mosh数据

**Comment by EveningLin** [comment]
@geopavlakos @BICHENG @liwenssss @vigorbird @GuiZhaoyang
 where can i get the json file in the code
`                    json_file = os.path.join(openpose_path, 'coco',
                        imgname.replace('.jpg', '_keypoints.json'))`

**Comment by GloryyrolG** [comment]
> No MoSh results are available for MPI-INF-3DHP. In that case, we fit SMPL to keypoints. Since ground truth is not very accurate, we prefer to use OpenPose predictions and fit SMPL to them for all viewpoints simultaneously.

Hi @geopavlakos  et al., Could you kindly release openpose detection of these data please? Thx & best,
