### ISSUE TITLE
problems about the docker images

### ISSUE THREAD

**Issue by QuteSaltyFish** [nkolot/SPIN#46]
after pulling the docker image and run the eval code, it said that I have a lot of libraries that are not installed. I don't know if I'm the only one encountered with this problem.

**Comment by QuteSaltyFish** [comment]
And after installing all the packages, I got the error
![Screenshot from 2020-01-17 01-30-54](https://user-images.githubusercontent.com/41997780/72548136-0d3e7380-38c9-11ea-9634-9f9308120795.png)

**Comment by arturbecker** [comment]
Hi, I had the same problem. In my opinion @nkolot it's not clear on the README that you have to install just a few of the packages on requirements.txt to get the Docker image working.
So far for me: **demo.py** needs just **freetype-py** and **pyglet** ; **eval.py** needs **neural-renderer-pytorch**, but it has to be installed with the **--no-deps** argument through pip, so that pip doesn't reinstall torch (this is important because it will install a torch version with another cuda version that doesn't work).

That said, I'm still stuck on making eval.py work on the provided Docker image. I could make it work with an off-the-shelf torch image though.

**Comment by arturbecker** [comment]
Also are you using **--gpus all** when running the container?

**Comment by QuteSaltyFish** [comment]
> Also are you using **--gpus all** when running the container?

Yes, I use --gpus all, I will try to install the neural-renderer-pytorch with --no-deps

**Comment by QuteSaltyFish** [comment]
> Hi, I had the same problem. In my opinion @nkolot it's not clear on the README that you have to install just a few of the packages on requirements.txt to get the Docker image working.
> So far for me: **demo.py** needs just **freetype-py** and **pyglet** ;
> **eval.py** needs **neural-renderer-pytorch**, but it has to be installed with the **--no-deps** argument through pip, so that pip doesn't reinstall torch (this is important because it will install a torch version with another cuda version that doesn't work).

Thank You very much! I can now run the evaluate code!

**Comment by QuteSaltyFish** [comment]
> Also are you using **--gpus all** when running the container?

By the way, do you have the h36m_fits.npy file? I don't know where to get it.
