### ISSUE TITLE
'data/static_fits/h36m_fits.npy' not found

### ISSUE THREAD

**Issue by QuteSaltyFish** [nkolot/SPIN#48]
When I run the train.py code in the docker,  it said this file not found. How can I get this file?

**Comment by ikvision** [comment]
Indeed human3.6 has licensing issues https://github.com/nkolot/SPIN/issues/20#issuecomment-561198241 
You may try to train without it https://github.com/nkolot/SPIN/issues/32#issuecomment-576392860

**Comment by GuiZhaoyang** [comment]
I have met your problem.I have produced the h36m_train.npz,but I did not find the code to produce h36m_fits.npy. Can you tell me how you solved the problem? @QuteSaltyFish

**Comment by ikvision** [comment]
h36m_fits.npy contains the best pseudo ground truth for h36m, it is used to populate fits_dict, and it is not published due to licensing issues.
As you train your model fits_dict gets updated and saved periodically. 
That mean that if you fine using the latest model and use --run_smplify it will at some point generate good fits for h36m.
Therefore, you can simply initialize the h36m fits_dict using with the mean parameters       
https://github.com/nkolot/SPIN/blob/b95a00a7c0147f2c5bee0874ba0972c6389b6f99/models/hmr.py#L86-L89    
Once h36m fits_dict doesn't get updated you can assume you reached the best pseudo ground truth

**Comment by GuiZhaoyang** [comment]
@ikvision Thanks for your advice.I think I can understand what you mean in general.But it seemed to modify much code in the training programming.May I could konw how to modify the code.In addition,is it possible to produce the h36m_fit.npy by running eval.py on human3.6m dataset.What is the format of the file, if applicable

**Comment by jakiroshah** [comment]
Hi, just had a question regarding the dimensions of the mean_params and the expected dimensions of fits_dict. While the former contains pose of dims 144, fits_dict expects pose to be of dims 72. I am having a hard time figuring out which pose params to discard - could you please help me with this?

Thank you!

**Comment by yanran11** [comment]
> I have met your problem.I have produced the h36m_train.npz,but I did not find the code to produce h36m_fits.npy. Can you tell me how you solved the problem? @QuteSaltyFish

I had a similar problem.How did you  generate h36m_fits.npy to train finally?Thank you！！

**Comment by yqq-jj** [comment]
How did you generate h36m_train.npz？@GuiZhaoyang
