### ISSUE TITLE
Bad results with partial bodies

### ISSUE THREAD

**Issue by EnricoBeltramo** [nkolot/SPIN#62]
I observed that there are good result with full bodies (especially if placed in front perspective), but there are often wrong result with partial body. There are some way or optimization to do to improve those cases?

**Comment by ikvision** [comment]
The algorithm expect a full body to be about 200 pixels out of the 224 and centered
https://github.com/nkolot/SPIN/blob/b95a00a7c0147f2c5bee0874ba0972c6389b6f99/demo.py#L82-L86
For prediction on partial body it might be that bonding box is not centered on the X or Y dimensions due to incorrect padding.
I suppose that fine tuning with augmentation targeting partial body crop should improve the results too, but I didn't try it.

**Comment by nkolot** [comment]
Yes, indeed the model was not trained with partial body inputs. You can try something similar to HMR (use a discriminator) and include the images with partial bodies in training. From our experience it works very well.
