### ISSUE TITLE
How to get the static fits for the dataset?

### ISSUE THREAD

**Issue by Vincent-2017** [nkolot/SPIN#67]
Hello, in the paper you mentioned using [21] to initialize the dictionary, can you describe the method in detail? Thank you!

**Comment by nkolot** [comment]
The idea is simple:
We use a network similar to [21] that takes as input 2D keypoints and outputs SMPL parameters + the camera that aligns SMPL with the 2D keypoints. The only thing that changes is the number of input and output features. Everything else is the same.

For training, we did data augmentations like adding noise to the keypoints and randomly removing some keypoints to make it more robust because in some datasets (e.g. COCO) often times there are missing annotations.

After training the network you can feed in the ground truth keypoints of each dataset, predict SMPL parameters + camera and use those as initialization for the SMPLify.

I hope that this helps.

**Comment by ku294714** [comment]
Hello, On the same question as above, what dataset did you use to train the above model (how did you manage GT SMPL params)  and how is it related to SMPL_MEAN_PARAMS.npz used in HMR model?
