### ISSUE TITLE
Puzzles about 3DPW

### ISSUE THREAD

**Issue by penincillin** [nkolot/SPIN#83]
Thanks for the great paper and code releasing !

I just noticed that you have evaluated on 3DPW dataset but haven't trained on it. 

So I am just wondering is there any reason for not training on the 3DPW ?

Thanks !

**Comment by ikvision** [comment]
You might want to have a look at VIBE that is build on top of SPIN and trains with 3DPW
https://github.com/mkocabas/VIBE/blob/4cd231b8f0e29eed4f75214750aa63fb9d531aed/scripts/prepare_training_data.sh#L14

**Comment by penincillin** [comment]
Thanks for your rapid reply. I will take a look !

**Comment by penincillin** [comment]
@geopavlakos @ikvision Thanks for answer my questions ! I am just puzzled about why 3DPW is not used in training ? Is there any reason for this ? Since I am considering adding 3DPW in training. Thanks !

**Comment by geopavlakos** [comment]
We avoided using 3DPW for training in order to remain comparable with the approaches of [Table 1.](https://arxiv.org/pdf/1909.12828.pdf) They also report results on 3DPW, and none of them uses 3DPW for training.
If you train on 3DPW, performance on the same dataset will probably improve (as [VIBE](https://arxiv.org/abs/1912.05656) shows too), but we wanted to stay comparable with everyone else.

**Comment by penincillin** [comment]
@geopavlakos Get it ! Thanks for your reply !
