### ISSUE TITLE
training spin

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [nkolot/SPIN#97]
Hi,

Thanks for a great work and codebase.
I want to retrain SPIn without human 3.6
I downloaded all datasets, and did not preprocess them as you mention **`With the exception of Human3.6M, we already provide these files and you can get them by running the fetch_data.sh script.`**.

Launching the train shell command `python3 train.py --name train_example --pretrained_checkpoint=data/model_checkpoint.pt --run_smplify` yields exceptions in the data loading [here](https://github.com/nkolot/SPIN/blob/master/datasets/base_dataset.py#L186) :

```
/home/tgroueix/Documents/VIBE/data/mpi_inf_3dhp/S1/Seq2/imageFrames/video_8/frame_010464.jpg
/home/tgroueix/Documents/VIBE/data/mpi_inf_3dhp/S2/Seq2/imageFrames/video_8/frame_005091.jpg
/home/tgroueix/Documents/VIBE/data/mpi_inf_3dhp/S3/Seq1/imageFrames/video_6/frame_009911.jpg
```
Indeed these files do not exist off-the-shelf after download.

Do you confirm that i can train without preprocessing the datasets and if so, what is it the correct shell command? 
Thanks for your kind help,
Thibault

**Comment by geopavlakos** [comment]
Hi Thibault,
Since this was not very clear in the original message, did you preprocess the data following the instructions of this repo, or not? If the preprocessing is different, is it possible that this is why you miss these images? You shouldn't see an error from the dataloader with missing frames.

**Comment by ThibaultGROUEIX** [comment]
Thanks for getting back to me!
No i do not preprocess the data following the instructions of the repo. I understood from the bolded extract of the doc above that it was optional. Maybe i misunderstood?

**Comment by nkolot** [comment]
So the preprocessing part is necessary to make sure that all data is in place. I can see from your logs that you are probably using the images from VIBE and there could be a few things that can go wrong. For example, different papers might keep different frames from each dataset (because of how subsampling of the original videos is performed). In order to extract the frames that we use from the original dataset files you need to run our preprocessing scripts. This way you can ensure that everything is in place when it needs to be loaded. Let me know if you have any further questions.

**Comment by ThibaultGROUEIX** [comment]
Ok ! I was a bit confused by the [doc here](https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/README.md#generate-dataset-files). Thanks a lot for the clarification!
